# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 100

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 200

[[main]]
  name = "Coding"
  url = "coding/"
  weight = 300
  identifier = "coding"

[[main]]
  name = "Python"
  url = "coding/python/"
  weight = 310
  parent = "coding"

[[main]]
  name = "Java"
  url = "coding/java/"
  weight = 320
  parent = "coding"

[[main]]
  name = "Go"
  url = "coding/go/"
  weight = 330
  parent = "coding"

[[main]]
  name = "JavaScript"
  url = "coding/javascript/"
  weight = 340
  parent = "coding"

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

[[main]]
  name = "Linux"
  url = "linux/"
  weight = 400

[[main]]
  name = "DevOps"
  url = "devops/"
  weight = 500

[[main]]
  name = "Networking"
  url = "networking/"
  weight = 600

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 700

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 800

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 900
